chore: bump duty to v1.0.1318 (#3166)
* chore: bump duty to v1.0.1318

* fix: bump controller-runtime

duty bumped client-go which isn't comaptible with the existin
controller-runtime version.

```
$ make dev
CGO_ENABLED=0 go build -v -o ./.bin/incident-commander -gcflags="all=-N -l" main.go
sigs.k8s.io/controller-runtime/pkg/cache
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:363:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:380:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:397:9: cannot use handles (variable of struct type handlerRegistration) as "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration value in return statement: handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
../../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.23.3/pkg/cache/multi_namespace_cache.go:402:17: impossible type assertion: h.(handlerRegistration)
	handlerRegistration does not implement "k8s.io/client-go/tools/cache".ResourceEventHandlerRegistration (missing method HasSyncedChecker)
make: *** [dev] Error 1
```

---------

Co-authored-by: Aditya Thebe <contact@adityathebe.com>