feat: access database connection from the context (#417)
* feat: access database connection from the context

* Refactored upstream test
* Removed vars from testutils. (Since the tests are now moved to the
  events package, the vars can be inside the package itself.)

* fix: db nil check in context

* make use of api.Context in other places

* chore: address review comment

* fix: NewContext() call

* weird fix but ok

with the ctx object passed to context.WithTimeout we get stack overflow
error

```
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0xc021cfe378 stack=[0xc021cfe000, 0xc041cfe000]
fatal error: stack overflow
```

* remove disablePostgrest flag

* bring back disablePostgrest flag and mark it as deprecated.

* Set http://localhost:3000 as the default postgrest URL